from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .source import CONFIG_DIR, CONFIG_FILE


@dataclass(frozen=True)
class InitFileResult:
    path: Path
    status: str


@dataclass(frozen=True)
class InitResult:
    written: int
    skipped: int
    files: list[InitFileResult]


def sample_files(root: Path) -> dict[Path, str]:
    ai_dir = root / CONFIG_DIR
    return {
        ai_dir / CONFIG_FILE: """project:\n  name: MMY RuleBridge\n  type: ai-agent-config-tool\n\nrules:\n  include:\n    - rules/common.md\n    - rules/security.md\n    - rules/git.md\n\ntargets:\n  - codex\n  - claude\n  - cursor\n  - generic\n  - git\n  - mcp\n  - zcode\n  - trae\n  - codebuddy\n  - workbuddy\n\nprofile: dev\n""",
        ai_dir / "rules" / "common.md": """# Common Rules\n\n- Respond clearly and keep technical terms, paths, commands, and logs unchanged.\n- Prefer small, reversible changes.\n- Match the surrounding code style.\n""",
        ai_dir / "rules" / "security.md": """# Security Rules\n\n- Do not expose secrets, tokens, passwords, cookies, or private keys.\n- Ask before writing outside the project root.\n- Do not modify user-level agent configuration by default.\n""",
        ai_dir / "rules" / "git.md": """# Git Rules\n\n- Check `git status` before staging or committing.\n- Check `git diff --cached` before committing.\n- Do not push unless explicitly requested.\n""",
        ai_dir / "skills" / "example-skill" / "SKILL.md": """---\nname: example-skill\ndescription: Example documentation-only skill generated by RuleBridge.\n---\n\n# Example Skill\n\nUse this skill as a template for reusable AI-agent workflows.\n""",
        ai_dir / "commands" / "review.md": """---\ndescription: Review the given scope with project rules.\nargument-hint: "[scope]"\nskills:\n  - example-skill\n---\n\nReview this scope using the project rules and report risks first:\n\n$ARGUMENTS\n""",
        ai_dir / "hooks" / "before_commit.yaml": """event: before_commit\nsteps:\n  - type: command\n    run: git status --short\n  - type: secret_scan\ntargets:\n  - git\n  - codex\n  - claude\n""",
        ai_dir / "hooks" / "before_push.yaml": """event: before_push\nsteps:\n  - type: command\n    run: git status --short\n  - type: require_confirmation\n    message: Confirm pushed commits contain no secrets and target branch is correct.\ntargets:\n  - git\n  - codex\n  - claude\n""",
        ai_dir / "mcp" / "servers.yaml": """servers:\n  filesystem:\n    enabled: true\n    command: npx\n    args:\n      - -y\n      - "@modelcontextprotocol/server-filesystem"\n      - .\n    env:\n      NODE_ENV: production\n    targets:\n      - mcp\n      - codebuddy\n      - workbuddy\n""",
        ai_dir / "packs" / "example-pack" / "pack.yaml": """name: example-pack\ntitle: Example Optional Pack\ndescription: Disabled sample pack. Enable manually after review.\nlicense: review-required\nenabled: false\npriority: community\ntargets:\n  - codex\n  - claude\n  - cursor\n""",
    }


def init_source(root: Path | str, *, force: bool = False) -> InitResult:
    root_path = Path(root).resolve()
    written = 0
    skipped = 0
    results: list[InitFileResult] = []
    for path, content in sample_files(root_path).items():
        if path.exists() and not force:
            skipped += 1
            results.append(InitFileResult(path.relative_to(root_path), "skipped"))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        written += 1
        results.append(InitFileResult(path.relative_to(root_path), "created"))
    return InitResult(written=written, skipped=skipped, files=results)
