from __future__ import annotations

from pathlib import Path

from rulebridge.adapters.base import TargetAdapter
from rulebridge.models import GeneratedFile, HookSpec, RenderContext

EVENT_TO_FILE = {
    "before_commit": "pre-commit",
    "before_push": "pre-push",
}

SECRET_SCAN = r'''if git diff --cached | grep -Ei "(api_key|apikey|token|secret|password|passwd|private_key|client_secret)" >/dev/null; then
  echo "RuleBridge: possible secret found in staged diff." >&2
  echo "Review staged changes before committing." >&2
  exit 1
fi'''


def shell_quote(text: str) -> str:
    return "'" + text.replace("'", "'\"'\"'") + "'"


def render_step(step: dict[str, object]) -> list[str]:
    step_type = str(step.get("type", "command"))
    if step_type == "command":
        run = str(step.get("run", "")).strip()
        return [run] if run else []
    if step_type == "secret_scan":
        return [SECRET_SCAN]
    if step_type == "require_confirmation":
        message = str(step.get("message", "Continue?"))
        quoted = shell_quote(message)
        return [
            f"printf '%s [y/N] ' {quoted}",
            "read -r rulebridge_answer",
            "case \"$rulebridge_answer\" in [yY]|[yY][eE][sS]) ;; *) echo 'RuleBridge: cancelled.' >&2; exit 1 ;; esac",
        ]
    if step_type == "message":
        message = str(step.get("message", "")).strip()
        return [f"echo {shell_quote(message)}"] if message else []
    return [f"echo {shell_quote(f'RuleBridge: unsupported hook step type {step_type}; skipped.')} >&2"]


def render_git_hook(hook: HookSpec) -> str:
    lines = [
        "#!/usr/bin/env sh",
        "set -eu",
        f"# Generated by RuleBridge from {hook.path}",
        f"echo {shell_quote(f'RuleBridge hook: {hook.event}')}",
        "",
    ]
    for index, step in enumerate(hook.steps, start=1):
        lines.append(f"# step {index}: {step.get('type', 'command')}")
        lines.extend(render_step(step))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


class GitAdapter(TargetAdapter):
    name = "git"

    def render(self, context: RenderContext) -> list[GeneratedFile]:
        files: list[GeneratedFile] = []
        for hook in context.source.hooks:
            file_name = EVENT_TO_FILE.get(hook.event)
            if not file_name:
                continue
            if hook.targets and "git" not in hook.targets:
                continue
            files.append(GeneratedFile(path=Path(".githooks") / file_name, content=render_git_hook(hook), managed=False))
        return files
